# basic options
title: Documenation Repository
author:
  name: Francis Ferguson
  email: francis.ferguson@lumen.com
description: Examaple 

# Build settings
markdown: kramdown
remote_theme: jekyll/minima
