# basic options
title: Documenation Repository
author:
  name: Francis Ferguson
  email: francis.ferguson@lumen.com
description: Example

# Build settings
markdown: kramdown
remote_theme: jekyll/minima

theme: jekyll-theme-time-machine